### ISSUE TITLE
Doesn't work any more

### ISSUE THREAD

**Issue by davidrhoderick** [TimPerry/acf-post-type-selector#27]
Adding it to a post results in the following error:

    Fatal error: Uncaught Error: Call to undefined function acf_force_type_array() in /srv/www/mvm/public_html/wp-content/plugins/acf-post-type-chooser-master/acf-post-type-chooser-v5.php:158 Stack trace: #0 /srv/www/mvm/public_html/wp-includes/class-wp-hook.php(286): acf_field_post_type_chooser->render_field(Array) #1 /srv/www/mvm/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #2 /srv/www/mvm/public_html/wp-includes/plugin.php(531): WP_Hook->do_action(Array) #3 /srv/www/mvm/public_html/wp-content/plugins/advanced-custom-fields-pro/includes/acf-hook-functions.php(105): do_action_ref_array('acf/render_fiel...', Array) #4 /srv/www/mvm/public_html/wp-includes/class-wp-hook.php(286): _acf_apply_hook_variations(Array) #5 /srv/www/mvm/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #6 /srv/www/mvm/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #7 /srv/www/mvm/public_html/wp-content/plugins/advanced-custom-fields-pro/includes/acf-field-functions in /srv/www/mvm/public_html/wp-content/plugins/acf-post-type-chooser-master/acf-post-type-chooser-v5.php on line 158
    The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.

**Comment by seemly** [comment]
A very delayed response, but your error message refers to a completely different plugin/codebase.

You also reported an error on that repository a month before this one:
https://github.com/reyhoun/acf-post-type-chooser/issues/2

This issue should be closed.

**Comment by TimPerry** [comment]
Also commenting here: Hey, yeah, sorry I no longer maintain this, so that other plugin you recommended sounds good to me.
